# Generated by Django 4.2.1 on 2023-05-19 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='adm_number',
        ),
    ]
